language: java
jdk:
  - openjdk8

before_install:
  - sudo apt-get install ant-optional 
script:
  
  - ant -lib lib/ 


notifications:
  email:
    recipients:
      - manuelsturla@gmail.com
      - diego.balestieri1998@gmail.com
      - Santiagolampropulos@gmail.com
      - flia_giampietri@yahoo.com
    on_failure: always
