language: java
jdk:
  - openjdk8

script:
  
  - ant test 


notifications:
  email:
    recipients:
      - manuelsturla@gmail.com
      - diego.balestieri1998@gmail.com
      - Santiagolampropulos@gmail.com
      - flia_giampietri@yahoo.com
    on_failure: always
