language: java
jdk:
  - openjdk8

before_install:
  - sudo apt-get install ant-optional 
script:
  - sudo mv ./lib/ant-junitlauncher-jar-1.10.5.jar ANT_HOME/lib
  - ant -lib "./lib" test 


notifications:
  email:
    recipients:
      - manuelsturla@gmail.com
      - diego.balestieri1998@gmail.com
      - Santiagolampropulos@gmail.com
      - flia_giampietri@yahoo.com
    on_failure: always
